# Azure Functions Github Action
name: 'Azure Functions'
description: 'Deploy Function App to Azure Functions'
inputs:
  app-name:
    description: 'Name of the Azure Function App'
    required: true
  runtime-stack:
    description: 'The operating system that the function will run on (windows, linux)'
    required: true
  function-runtime:
    description: 'The language that the function will use (dotnet, powershell, java, python, node)'
    required: true
  package:
    description: 'Path to package or folder. *.zip or a folder to deploy'
    required: false
    default: '.'
outputs:
  app-url:
    description: 'URL to work with your function app'
branding:
  icon: 'functionapp.svg'
runs:
  using: 'node12'
  main: 'lib/main.js'