name: SamplesCI

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Check Azure CLI Subscription Id'
      run: az account show --query id
    - name: 'Run Azure Functions Action'
      uses: ./functionapp
      with:
        app-name: 'hazeng-fa-hk-node-ded'
        runtime-stack: 'windows'
        function-runtime: 'node'
        package: './sample_node_functionapp'
        id: 'result'
    - name: 'Result'
      run: echo "The result is ${{ steps.result.outputs.functionapp-url }}"
