name: SamplesContainerCI

on:
  push:
    branches:
    - master

jobs:
  build-and-deploy:
    # ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
    # windows-latest, windows-2019, or windows-2016
    # macOS-latest or macOS-10.14
    runs-on: ubuntu-18.04
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Check Azure CLI Subscription Id'
      run: az account show --query id
    - name: 'Compose Customized DockerImage'
      run: |
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build ./sample_node_container_functionapp -t docker.io/rogerxman/test:serious3
        docker push docker.io/rogerxman/test:serious3
    - name: 'Run Azure Functions Action'
      uses: ./functionapp-container
      id: fa
      with:
        app-name: 'hazeng-fa-github-container-node'
        image: "docker.io/rogerxman/test:serious3"
    - name: 'Report Result'
      run: echo "FunctionApp URL ${{ steps.fa.outputs.app-url }}"
