# File: .github/workflows/workflow.yml
name: Test_E2E_WebApp

on:
  push:
    branches:
    - e2e-test

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master
    # install dependencies, build, and test
    - name: npm install, build, and test
      shell: pwsh
      run: |
        pushd tests/webapp
        npm install
        npm run build --if-present
        npm run test --if-present
        popd
    # deploy web app using publish profile credentials
    - uses: azure/appservice-actions/webapp@master
      with:
        app-name: hazeng-wa-github
        package: './tests/webapp'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}