name: Test_E2E_Python

on:
  push:
    branches:
    - master

# ubuntu-latest, ubuntu-18.04, or ubuntu-16.04
# windows-latest, windows-2019, or windows-2016
# macOS-latest or macOS-10.14
jobs:
  lin-con-python:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: 'pip install'
      shell: bash
      run: |
        pushd ./tests/python
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/python3.6/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@master
      id: fa
      with:
        app-name: 'hazeng-fa-github-lin-con-python'
        package: './tests/python'
    - name: 'Report HttpTrigger Result'
      shell: bash
      run: |
        sleep 60
        RESPONSE=$(curl "${{ steps.fa.outputs.app-url }}/api/HttpTrigger")
        if [ $RESPONSE == AWESOME ]; then
          exit 0
        fi
        exit 1
  lin-ded-python:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Setup Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: 'pip install'
      shell: bash
      run: |
        pushd ./tests/python
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/python3.6/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@master
      id: fa
      with:
        app-name: 'hazeng-fa-github-lin-ded-python'
        package: './tests/python'
    - name: 'Report HttpTrigger Result'
      shell: bash
      run: |
        sleep 60
        RESPONSE=$(curl "${{ steps.fa.outputs.app-url }}/api/HttpTrigger")
        if [ $RESPONSE == AWESOME ]; then
          exit 0
        fi
        exit 1
  container-python:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - name: 'Login via Azure CLI'
      uses: Azure/actions/login@master
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: 'Compose Customized DockerImage'
      shell: bash
      run: |
        docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
        docker build ./tests/python -t docker.io/rogerxman/github-action-e2e:python
        docker push docker.io/rogerxman/github-action-e2e:python
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-container-action@master
      id: fa
      with:
        app-name: 'hazeng-fa-github-container-python'
        image: "docker.io/rogerxman/github-action-e2e:python"
    - name: 'Report HttpTrigger Result'
      shell: bash
      run: |
        sleep 60
        RESPONSE=$(curl "${{ steps.fa.outputs.app-url }}/api/HttpTrigger")
        if [ $RESPONSE == AWESOME ]; then
          exit 0
        fi
        exit 1