on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello World change
    - uses: ./hello-world-action
      with:
        who-to-greet: 'Mundo'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"
